# Generated by Django 3.1.7 on 2021-03-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='book_title',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='ratings_amount',
            field=models.IntegerField(default=0),
        ),
    ]
