# Generated by Django 3.1.7 on 2021-03-11 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210307_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.CharField(default='unknown', max_length=100, unique=True),
        ),
    ]
